# -*- coding: utf-8 -*-
# Sources and teaching cards for content/q_rules.json (module "rules")

SOURCES = {
    "S1": {"title": "مرسوم بقانون اتحادي رقم 14 لسنة 2024 بشأن تنظيم السير والمرور (النص العربي)",
           "url": "https://uaelegislation.gov.ae/ar/legislations/2598/download",
           "publisher": "UAE Legislation portal", "date": "2024-09 (in force 2025-03-29)"},
    "S2": {"title": "Federal Decree-Law No. 14 of 2024 On Traffic Regulation (English text)",
           "url": "https://uaelegislation.gov.ae/en/legislations/2598/download",
           "publisher": "UAE Legislation portal", "date": "2024-09"},
    "S3": {"title": "Ministerial Resolution No. 130 of 1997, Executive Regulation of the Federal Traffic Law (English)",
           "url": "https://uaelegislation.gov.ae/en/legislations/1020/download",
           "publisher": "UAE Legislation portal", "date": "1997, listed in force, updated 2023-05"},
    "S4": {"title": "القرار الوزاري رقم 130 لسنة 1997 باللائحة التنفيذية لقانون السير والمرور (النص العربي)",
           "url": "https://uaelegislation.gov.ae/ar/legislations/1020/download",
           "publisher": "UAE Legislation portal", "date": "1997, updated 2023-05"},
    "S5": {"title": "Light Motor Vehicle Handbook, A Guide to Safe Driving, 7th edition",
           "url": "https://edi-uae.com/public/uploads/downloads/20190724133013RTA_Handbook_-_Light_Motor_Vehicle_(LMV)_-_English.pdf",
           "publisher": "RTA Licensing Agency (hosted by Emirates Driving Institute)", "date": "2016-01"},
    "S6": {"title": "كتيب المركبات الآلية الخفيفة، دليل للقيادة الآمنة، الطبعة 3",
           "url": "https://www.rta.ae/wpsv5/eservices/PDF_Catalog/Light_Motor_Handbook_AR.pdf",
           "publisher": "RTA Licensing Agency", "date": "2012-01"},
    "S7": {"title": "كتيب المركبات الآلية الخفيفة، الطبعة 8",
           "url": "https://www.drivedubai.ae/public/uploads/downloads/20210301161905RTA-Handbook-Light-Motor-Vechicle-Arabic.pdf",
           "publisher": "RTA Licensing Agency (hosted by Dubai Driving Center)", "date": "2021-03"},
    "S8": {"title": "New UAE traffic law: When should you give way, and when do you have the right of way?",
           "url": "https://gulfnews.com/living-in-uae/transport/new-uae-traffic-law-when-should-you-give-way-and-when-do-you-have-the-right-of-way-1.1730289189795",
           "publisher": "Gulf News", "date": "2024-10-31"},
    "S9": {"title": "Dubai: 5 rules to follow when driving in the fast lane",
           "url": "https://gulfnews.com/living-in-uae/transport/dubai-5-rules-to-follow-when-driving-in-the-fast-lane-2-1.1720015446210",
           "publisher": "Gulf News (Dubai Police, RTA)", "date": "2024-07-03"},
    "S10": {"title": "Dubai Police warn: Slow driving in fast lanes as dangerous as speeding",
            "url": "https://gulfnews.com/uae/transport/dubai-police-warn-slow-driving-in-fast-lanes-as-dangerous-as-speeding-dh400-fine-imposed-1.500256599",
            "publisher": "Gulf News (Dubai Police)", "date": "2025-09-04"},
    "S11": {"title": "Think you're following UAE lane rules? The driving mistakes that could get you fined",
            "url": "https://gulfnews.com/living-in-uae/transport/think-youre-following-uae-lane-rules-the-driving-mistakes-that-could-get-you-fined-1.500124462",
            "publisher": "Gulf News (RTA, Sharjah Police)", "date": "2025-05-12"},
    "S12": {"title": "Dubai Police: Let emergency vehicles go, every second matters",
            "url": "https://gulfnews.com/uae/dubai-police-let-emergency-vehicles-go-every-second-matters-1.66847995",
            "publisher": "Gulf News (Dubai Police)", "date": "2019-10-02"},
    "S13": {"title": "شرطة دبي تفسح الطريق أمام مركبات الطوارئ بـ«الأمل»",
            "url": "https://www.emaratalyoum.com/local-section/other/2019-10-03-1.1258016",
            "publisher": "Emarat Al Youm (Dubai Police)", "date": "2019-10-03"},
    "S14": {"title": "«لا تتردد.. افسح الطريق فورا» حملة مشتركة لمركبات الطوارئ والإسعاف",
            "url": "https://abudhabipolice.gov.ae/Media-Center/News/2025/05/29052025001",
            "publisher": "Abu Dhabi Police", "date": "2025-05-29"},
    "S15": {"title": "Dh3,000 fine, 30 days impoundment: Sharjah warns against blocking emergency vehicles",
            "url": "https://www.khaleejtimes.com/uae/emergencies/dh3000-fine-impoundment-blocking-emergency-vehicles",
            "publisher": "Khaleej Times (Sharjah Police)", "date": "2025-05-03"},
    "S16": {"title": "UAE: Give way to emergency vehicles or face Dh3,000 traffic fine",
            "url": "https://gulfnews.com/living-in-uae/transport/uae-give-way-to-emergency-vehicles-or-face-dh3000-traffic-fine-1.500247516",
            "publisher": "Gulf News (Abu Dhabi Police)", "date": "2025-08-27"},
    "S17": {"title": "طرق دبي تؤكد تعليمات ذراع التوقف للحافلات المدرسية",
            "url": "https://www.emaratalyoum.com/local-section/education/2026-04-21-1.2038053",
            "publisher": "Emarat Al Youm (RTA)", "date": "2026-04-21"},
    "S18": {"title": "Dubai School Bus Stop Arm Rules: what drivers must know",
            "url": "https://gulfnews.com/uae/transport/school-bus-stop-arm-rules-in-dubai-what-drivers-must-know-1.500514122",
            "publisher": "Gulf News (RTA)", "date": "2026-04-21"},
    "S19": {"title": "Abu Dhabi Police urge motorists to follow rules around school buses",
            "url": "https://www.thenationalnews.com/news/uae/2026/08/31/uae-school-bus-rules-drivers-parents-students-staff/",
            "publisher": "The National (Abu Dhabi Police)", "date": "2026-08-31"},
    "S20": {"title": "Dh1,000 fine in UAE: Police issue warning against violating school bus stop sign rules",
            "url": "https://www.khaleejtimes.com/uae/transport/dh1000-fine-in-uae-police-issue-warning-against-violating-school-bus-stop-sign-rules",
            "publisher": "Khaleej Times (Abu Dhabi Police)", "date": "2023-04-06"},
    "S21": {"title": "Tailgating in Dubai: rules explained",
            "url": "https://gulfnews.com/living-in-uae/transport/dubai-tailgating-fine-rules-1.500083210",
            "publisher": "Gulf News", "date": "2026-09-20"},
    "S22": {"title": "Don't use hazard lights and double safety distance during fog, Abu Dhabi Police advises",
            "url": "https://gulfnews.com/uae/dont-use-hazard-lights-and-double-safety-distance-during-fog-abu-dhabi-police-advises-1.82879145",
            "publisher": "Gulf News (Abu Dhabi Police)", "date": "2021-10-18"},
    "S23": {"title": "UAE: Driving with hazard lights on during fog? You could get fined; here's why",
            "url": "https://www.khaleejtimes.com/uae/weather/driving-fog-hazard-lights-tips",
            "publisher": "Khaleej Times", "date": "2025-11-20"},
    "S24": {"title": "UAE: Dh1,000 parking fine for these 5 violations",
            "url": "https://gulfnews.com/living-in-uae/transport/uae-dh1000-parking-fine-for-these-5-violations-1.1690295373406",
            "publisher": "Gulf News", "date": "2023-07-25"},
    "S25": {"title": "Roundabout Driving Rules in UAE: 2 and 3 lane roundabout guide",
            "url": "https://www.excellencedriving.com/en/blogs/roundabout-rules-uae",
            "publisher": "Excellence Driving (RTA-licensed institute, Dubai)", "date": "2025-12-09"},
    "S26": {"title": "UAE back to school: When must drivers stop for pedestrians?",
            "url": "https://www.emirates247.com/uae-guide/uae-back-to-school-when-must-drivers-stop-for-pedestrians-rules-fines-explained/5011",
            "publisher": "Emirates 24/7", "date": "2026-08-28"},
    "S27": {"title": "UAE: Stricter fines, potential jail time for crossing the road from non-designated areas",
            "url": "https://gulfnews.com/living-in-uae/transport/uae-stricter-fines-potential-jail-time-for-crossing-the-road-from-non-designated-areas-1.1730381813582",
            "publisher": "Gulf News", "date": "2024-10-31"},
    "S28": {"title": "Ambulance behind you in the UAE? How to give way",
            "url": "https://www.emirates247.com/uae-guide/ambulance-behind-you-in-the-uae-how-to-give-way-and-avoid-a-dh3000-fine/5032",
            "publisher": "Emirates 24/7 (Abu Dhabi Police campaign)", "date": "2026-08-29"},
}

# (topic, level, title, body, key or "", src, confidence)
CARDS = [
    # roundabouts
    ("roundabouts", 1, "اتجاه الدوران في الدوار",
     "السير في الإمارات على اليمين، لذلك تدخل الدوار بالانعطاف يمينا وتدور عكس عقارب الساعة، والجزيرة الوسطى تبقى على يسارك دائما",
     "عكس عقارب الساعة", ["S1", "S6"], "high"),
    ("roundabouts", 1, "من له الأولوية في الدوار؟",
     "المركبات التي تدور داخل الدوار لها الأولوية، وهي تأتيك من يسارك، خفف وانظر يسارا وادخل عندما تجد فجوة آمنة",
     "الأولوية للقادم من اليسار", ["S1", "S2", "S6"], "high"),
    ("roundabouts", 2, "المخرج الأول: الانعطاف يمينا",
     "اقترب في المسار الأيمن، وأعط إشارة اليمين من بداية الاقتراب، وابق في المسار الأيمن حتى تخرج",
     "المسار الأيمن وإشارة اليمين", ["S6", "S25"], "high"),
    ("roundabouts", 3, "الاستمرار إلى الأمام",
     "اختر قبل الدخول المسار الذي يوصلك إلى مخرجك حسب الأسهم (في الدوار ذي الثلاثة مسارات غالبا الأوسط)، ولا تعط إشارة عند الدخول، ثم أعط إشارة اليمين بعد أن تتجاوز المخرج الذي يسبق مخرجك",
     "إشارة اليمين بعد المخرج السابق", ["S6", "S25"], "medium"),
    ("roundabouts", 3, "الانعطاف يسارا والالتفاف",
     "للمخرج الثالث (يسارا) أو للعودة من الطريق نفسه: المسار الأيسر، وتبقى فيه، ثم تعطي إشارة اليمين بعد أن تتجاوز المخرج الذي يسبق مخرجك",
     "المسار الأيسر", ["S6", "S25"], "medium"),
    ("roundabouts", 2, "ممنوعات داخل الدوار",
     "ممنوع تغيير المسار داخل الدوار، وممنوع التجاوز فيه، وممنوع الوقوف على بعد يقل عن 15 مترا منه",
     "15 مترا", ["S3", "S4", "S25"], "high"),
    ("roundabouts", 4, "طوارئ أو شاحنة عند الدوار",
     "إذا اقتربت مركبة طوارئ فلا تدخل الدوار، وإذا كنت داخله فاخرج من أقرب مخرج، والشاحنات الطويلة قد تشغل أكثر من مسار فلا تسر بجانبها",
     "", ["S12", "S14", "S5"], "high"),
    # priority
    ("priority", 1, "الطريق الرئيسي أولا",
     "عند التقاء طريق رئيسي بطريق فرعي بلا لوحات ولا إشارات، الأولوية للمركبات القادمة من الطريق الرئيسي",
     "الرئيسي قبل الفرعي", ["S1", "S2", "S3"], "high"),
    ("priority", 3, "طرق متساوية بلا لوحات",
     "إذا تساوت الطرق في المرتبة ولا توجد لوحات ولا إشارات، فالأولوية للقادم من الجهة اليسرى: تنتظر المركبة التي تأتي من يسارك، والمركبة التي على يمينك تنتظرك",
     "الأولوية للقادم من اليسار", ["S1", "S2", "S3", "S8"], "high"),
    ("priority", 1, "«قف» و«أفسح الطريق»",
     "عند «قف» تتوقف تماما عند الخط ثم تعطي الأولوية للجميع، وعند «أفسح الطريق» تخفف وتتوقف إذا لزم وتعطي الأولوية",
     "", ["S6"], "high"),
    ("priority", 2, "الانعطاف يسارا والالتفاف",
     "من ينعطف يسارا يترك المركبات القادمة من الاتجاه المقابل تمر أولا، ومن يلتف للخلف يعطي الأولوية لكل المركبات والمشاة",
     "", ["S3", "S6"], "high"),
    ("priority", 2, "الخروج من موقف أو طريق خاص",
     "عند الدخول إلى الطريق من موقف أو محطة وقود أو طريق خاص تعطي الأولوية لكل المركبات على الطريق، وتدخل فقط عندما يكون ذلك آمنا",
     "", ["S6", "S3"], "high"),
    ("priority", 3, "الأولوية ليست عنادا",
     "حتى لو كانت الأولوية لك، اللائحة تطلب منك ألا تتمسك بها وأن تتوقف إذا كان ذلك يمنع ارتباكا أو حادثا",
     "", ["S3"], "high"),
    ("priority", 4, "مركبات لها أولوية بحكم القانون",
     "الترتيب في المادة 6: المواكب الرسمية، ثم الدفاع المدني أثناء الواجب، ثم الإسعاف أثناء مهامه، ثم القوافل العسكرية، ثم الشرطة عند استخدام أصوات وأضواء التحذير، ثم مركبات الخدمات الضرورية",
     "", ["S1", "S2"], "high"),
    # lanes
    ("lanes", 1, "الزم اليمين",
     "السير في الإمارات على الجانب الأيمن، والمركبات البطيئة تلتزم أقصى المسار الأيمن",
     "", ["S3"], "high"),
    ("lanes", 1, "المسار الأيسر للتجاوز",
     "استخدم المسار الأيمن عادة، والمسار الأيسر للتجاوز فقط ثم عد إلى اليمين، وأفسح الطريق للمركبة الأسرع خلفك حتى لو كنت ضمن السرعة المحددة",
     "", ["S5", "S9", "S10"], "high"),
    ("lanes", 2, "تغيير المسار بأمان",
     "مرآة، ثم إشارة في وقت كاف، ثم التفاتة رأس إلى النقطة العمياء، ثم انتقال هادئ، والإشارة لا تعطيك حق الانتقال إذا لم يكن آمنا",
     "مرآة، إشارة، التفاتة", ["S5", "S6", "S3"], "high"),
    ("lanes", 2, "الخط المتصل",
     "الخط المتصل يمنع العبور والتجاوز إلا في حالة طارئة، ابق على يمينه",
     "", ["S6", "S11"], "high"),
    ("lanes", 3, "البطء في المسار السريع",
     "القيادة ببطء في المسار السريع خطيرة مثل السرعة الزائدة، لأنها تجبر الآخرين على الفرملة أو تغيير المسار فجأة",
     "", ["S5", "S10"], "high"),
    ("lanes", 3, "مسارات الحافلات في دبي",
     "المسارات المطلية بالأحمر مخصصة للحافلات وسيارات الأجرة ومركبات الطوارئ، وليست للسيارات الخاصة",
     "", ["S6"], "medium"),
    # emergency-vehicles
    ("emergency-vehicles", 1, "افسح الطريق فورا",
     "عند سماع الصفارة أو رؤية الأضواء الوامضة الحمراء والزرقاء: التزم الجانب الأيمن وخفف السرعة وتوقف إذا لزم",
     "", ["S3", "S5"], "high"),
    ("emergency-vehicles", 2, "طريق سريع أو طريق داخلي",
     "على الطرق السريعة تسير مركبات الطوارئ في المسار الأيسر فتنتقل أنت يمينا، وفي الطرق الداخلية تتحرك المركبات يمينا أو يسارا لتفتح ممرا في الوسط",
     "", ["S12", "S14"], "high"),
    ("emergency-vehicles", 3, "عند الإشارة الحمراء والتقاطع",
     "أفسح المجال دون أن تقطع الإشارة الحمراء، وإذا كانت إشارتك خضراء ومركبة طوارئ تعبر التقاطع فتوقف واتركها تمر",
     "", ["S12", "S15", "S14"], "high"),
    ("emergency-vehicles", 3, "عند الدوار",
     "لا تدخل الدوار إذا اقتربت منه مركبة طوارئ، وإذا كنت داخله فتابع واخرج من أقرب مخرج",
     "", ["S12", "S14"], "high"),
    ("emergency-vehicles", 2, "لا تلحق بها",
     "ممنوع السير خلف مركبة الطوارئ للاستفادة من الطريق المفتوح، وشرطة دبي تخالف هذا السلوك",
     "", ["S12", "S13"], "high"),
    ("emergency-vehicles", 4, "كتف الطريق ليس لك",
     "عند الازدحام قد تستخدم مركبة الطوارئ كتف الطريق، فلا تنتقل إليه، وفي الطريق بمسار واحد لكل اتجاه تحرك إلى أقصى اليمين دون الخروج إلى الكتف",
     "", ["S14", "S16", "S28"], "high"),
    # overtaking
    ("overtaking", 1, "التجاوز من اليسار",
     "التجاوز في الإمارات من اليسار فقط، والاستثناء الوحيد: مركبة أعطت إشارة يسار وتحركت لتنعطف يسارا، فتمر من يمينها إذا كانت المساحة كافية",
     "من اليسار", ["S3", "S4"], "high"),
    ("overtaking", 2, "قبل أن تتجاوز",
     "تأكد أن الطريق أمامك واضح، ولا خطر من الاتجاه المقابل، ولا أحد خلفك بدأ يتجاوزك، وأعط الإشارة، واترك مسافة كافية قبل العودة",
     "", ["S3"], "high"),
    ("overtaking", 2, "أماكن ممنوع فيها التجاوز",
     "المنعطفات، قمم المرتفعات والمنحدرات، الطرق الزلقة، قرب ممرات المشاة، التقاطعات والدوارات والميادين، عند الازدحام أو ضعف الرؤية، وحيث توجد لوحة منع أو خط متصل",
     "", ["S3", "S4", "S11"], "high"),
    ("overtaking", 2, "عندما يتجاوزك أحد",
     "خفف سرعتك قليلا والتزم يمين مسارك، ولا تزد سرعتك لتمنعه",
     "", ["S3"], "high"),
    ("overtaking", 3, "الدراجات الهوائية والنارية",
     "تجاوزها فقط إذا استطعت الانتقال يسارا بأمان تاركا مترا واحدا على الأقل",
     "متر واحد على الأقل", ["S5", "S6"], "high"),
    ("overtaking", 4, "تجاوز ممنوع دائما",
     "لا تتجاوز من كتف الطريق، ولا تتجاوز حافلة مدرسية متوقفة وذراعها مفتوح، وتجنب التجاوز في الضباب",
     "", ["S11", "S19", "S22"], "high"),
    # speed
    ("speed", 1, "رقم اللوحة حد أقصى",
     "الرقم على لوحة السرعة هو أقصى سرعة في الظروف الجيدة، وعليك أن تخفف حسب الطريق والطقس والرؤية وحالة المركبة",
     "", ["S5", "S3"], "high"),
    ("speed", 2, "السرعات المعتادة",
     "حسب دليل هيئة الطرق: 40 أو 60 أو 80 كم/ساعة داخل المدن، و100 أو 120 كم/ساعة على الطرق السريعة، والمرجع دائما اللوحة المنصوبة",
     "المدن 40 إلى 80، السريعة 100 إلى 120", ["S5"], "high"),
    ("speed", 2, "أماكن تخفف فيها وجوبا",
     "الأحياء السكنية، المنعطفات، التقاطعات، ممرات المشاة، مداخل المدارس والمستشفيات، عند الاقتراب من الحيوانات، وعند ضعف الرؤية",
     "", ["S3", "S1"], "high"),
    ("speed", 3, "الحد الأدنى للسرعة",
     "بعض الطرق عليها لوحة حد أدنى للسرعة، وممنوع أن تسير أبطأ منها في الظروف العادية، والبطء في المسار السريع خطر",
     "", ["S3", "S6", "S5"], "high"),
    ("speed", 4, "السرعة ومسافة التوقف",
     "حسب دليل هيئة الطرق تحتاج حوالي 33 مترا لتتوقف من 60 كم/ساعة، وحوالي 130 مترا من 120 كم/ساعة، أي أن ضعف السرعة يعني تقريبا 4 أضعاف المسافة",
     "60 كم/ساعة: 33 مترا، 120 كم/ساعة: 130 مترا", ["S5", "S6"], "high"),
    # distance
    ("distance", 1, "قاعدة الثانيتين",
     "اترك ثانيتين على الأقل خلف المركبة التي أمامك في الظروف الجيدة",
     "ثانيتان على الأقل", ["S5", "S21"], "high"),
    ("distance", 2, "كيف تقيس المسافة",
     "اختر علامة ثابتة مثل عمود أو لوحة، وعد الثواني من لحظة مرور المركبة التي أمامك بها حتى تصل أنت إليها",
     "", ["S5", "S21"], "high"),
    ("distance", 2, "متى تزيد المسافة",
     "في المطر اجعلها 4 ثوان، وفي الضباب ضاعفها، وزدها كذلك على الطرق غير المعبدة وعند ضعف الرؤية",
     "المطر: 4 ثوان", ["S6", "S7", "S22", "S5"], "high"),
    ("distance", 3, "مم تتكون مسافة التوقف؟",
     "مسافة التوقف تتكون من مسافة رد الفعل (من رؤية الخطر حتى الضغط على المكابح) ومسافة الكبح (من الضغط حتى توقف المركبة)",
     "", ["S5", "S6"], "high"),
    ("distance", 3, "ما يطيل مسافة التوقف",
     "السرعة العالية، والطريق المبتل أو الزلق، والإطارات الممسوحة (عمق نقشة أقل من 1.5 ملم)، والتعب",
     "", ["S5"], "high"),
    ("distance", 4, "خلف الشاحنات",
     "الشاحنات والحافلات تحتاج مسافة أطول لتتوقف، وخلفها مباشرة منطقة عمياء، وإذا لم تر وجه السائق في مرآته فهو لا يراك",
     "", ["S5"], "high"),
    # turning
    ("turning", 1, "الإشارة في وقت كاف",
     "أعلن نيتك بالإشارة قبل الانعطاف أو تغيير المسار في وقت كاف، فالإشارة إعلام وليست أولوية",
     "", ["S3"], "high"),
    ("turning", 2, "الانعطاف يمينا",
     "اقترب قدر الإمكان من الحافة اليمنى للطريق، وخفف السرعة، وانتبه للمشاة والدراجات",
     "", ["S3", "S6"], "high"),
    ("turning", 2, "الانعطاف يسارا",
     "في طريق باتجاهين اقترب من منتصف الطريق، وفي طريق باتجاه واحد من أقصى اليسار، واترك المركبات المقابلة تمر أولا، ثم انعطف قريبا من يسار منتصف التقاطع",
     "", ["S3", "S6"], "high"),
    ("turning", 3, "الالتفاف للخلف",
     "من المسار الأيسر أو المسار المخصص للالتفاف، وممنوع عند الخط المتصل أو لوحة منع الالتفاف، وتعطي الأولوية لكل المركبات والمشاة",
     "", ["S6", "S3"], "medium"),
    ("turning", 3, "المشاة عند الانعطاف",
     "عندما تنعطف إلى شارع آخر خفف سرعتك، وتوقف حتى يعبر المشاة الذين بدؤوا العبور",
     "", ["S3", "S1"], "high"),
    ("turning", 4, "المركبات الطويلة",
     "الشاحنة أو الحافلة تحتاج مساحة أكبر للانعطاف وقد تشغل أكثر من مسار، فلا تدخل بجانبها عند انعطافها",
     "", ["S5"], "high"),
    # highway
    ("highway", 1, "فاتك المخرج؟",
     "لا ترجع للخلف ولا تتوقف، تابع إلى المخرج التالي",
     "", ["S5"], "high"),
    ("highway", 2, "الدخول إلى الطريق السريع",
     "استخدم مسار الدخول لتزيد سرعتك مبكرا حتى تقارب سرعة الطريق، ثم اندمج في فجوة آمنة، فالأولوية للمركبات على الطريق الرئيسي",
     "", ["S5", "S1", "S3"], "high"),
    ("highway", 2, "الخروج من الطريق السريع",
     "أعط الإشارة مبكرا، وادخل مسار الخروج من بدايته، وخفف سرعتك داخله، ولا تعبر الخطوط المائلة",
     "", ["S5"], "high"),
    ("highway", 1, "كتف الطريق",
     "كتف الطريق للمركبات المعطلة وخدمات الطوارئ فقط، وممنوع السير أو التجاوز عليه",
     "", ["S11", "S14"], "high"),
    ("highway", 3, "المسارات على الطريق السريع",
     "سر في المسارات اليمنى واستخدم الأيسر للتجاوز، والتزم بلوحة الحد الأدنى للسرعة إن وجدت",
     "", ["S5", "S9", "S3"], "high"),
    # pedestrians
    ("pedestrians", 1, "ممر المشاة",
     "خفف عند ممر المشاة، وتوقف حتى يكمل المشاة الذين بدؤوا العبور، ولا تقف فوق الممر",
     "", ["S1", "S3"], "high"),
    ("pedestrians", 2, "الأطفال وكبار السن",
     "الأطفال صغار ويصعب رؤيتهم وتصرفاتهم مفاجئة، وكبار السن أبطأ وقد لا يرون جيدا، فأعطهم وقتا ومساحة",
     "", ["S5", "S6"], "high"),
    ("pedestrians", 2, "قرب المدارس والمستشفيات",
     "القانون يلزمك بتخفيف السرعة عند مداخل ومخارج المؤسسات التعليمية والصحية",
     "", ["S1", "S2"], "high"),
    ("pedestrians", 3, "طرق تزيد سرعتها على 80",
     "القانون يمنع المشاة من عبور الطرق التي تزيد سرعتها المقررة على 80 كم/ساعة من غير الأماكن المخصصة، لكن انتباهك كسائق يبقى واجبا",
     "أكثر من 80 كم/ساعة", ["S1", "S27"], "high"),
    ("pedestrians", 4, "لا تتجاوز قرب الممر",
     "ممنوع التجاوز قرب ممرات المشاة، فالمركبة المتوقفة أو البطيئة قد تخفي مشاة يعبرون أمامها",
     "", ["S3"], "high"),
    # school-bus
    ("school-bus", 1, "ذراع «قف»",
     "عندما تفتح الحافلة المدرسية ذراع «قف» وتومض أضواؤها، توقف تماما",
     "", ["S17", "S18"], "high"),
    ("school-bus", 2, "5 أمتار على الأقل",
     "توقف على بعد 5 أمتار على الأقل من الحافلة المدرسية التي فتحت ذراع «قف»",
     "5 أمتار", ["S17", "S18", "S20"], "high"),
    ("school-bus", 3, "أي اتجاه يتوقف؟",
     "في الطريق غير المقسم تتوقف المركبات في الاتجاهين، وفي الطريق المقسم بفاصل تتوقف المركبات التي خلف الحافلة فقط",
     "", ["S17", "S18", "S19"], "high"),
    ("school-bus", 3, "متى تتحرك؟",
     "بعد أن يعبر كل الطلاب إلى منطقة آمنة، ويغلق الذراع، وتنطفئ الأضواء الوامضة",
     "", ["S17", "S18"], "high"),
    ("school-bus", 4, "لا تتجاوزها أبدا",
     "لا تتجاوز حافلة مدرسية متوقفة لإنزال الطلاب أو صعودهم حتى لو بدا المسار الآخر فارغا",
     "", ["S19", "S5"], "high"),
    # vulnerable
    ("vulnerable", 1, "الأكثر عرضة للخطر",
     "المشاة وراكبو الدراجات الهوائية والنارية والأطفال وكبار السن لا يحميهم هيكل مركبة، فانتبه لهم أكثر",
     "", ["S5", "S6"], "high"),
    ("vulnerable", 2, "الدراجات صغيرة",
     "الدراجات الهوائية والنارية صغيرة ويصعب رؤيتها، فانظر في المرايا والتفت إلى النقطة العمياء قبل تغيير المسار أو الانعطاف",
     "", ["S5"], "high"),
    ("vulnerable", 2, "متر واحد عند التجاوز",
     "عند تجاوز دراجة هوائية أو نارية اترك مترا واحدا على الأقل، وإذا لم تكن المساحة كافية فانتظر خلفها",
     "متر واحد", ["S5", "S6"], "high"),
    ("vulnerable", 3, "مناطق الشاحنة العمياء",
     "أمامها مباشرة، وخلفها لمسافة طويلة، وعلى جانبيها، وإذا لم تر وجه السائق في مرآته فهو لا يراك",
     "", ["S5"], "high"),
    ("vulnerable", 3, "الحيوانات على الطريق",
     "خفف سرعتك عند الاقتراب من الحيوانات أو المرور بها، ومنها الجمال قرب الطرق الخارجية",
     "", ["S3"], "high"),
    # parking
    ("parking", 1, "كيف تقف",
     "قف بهدوء قرب الحافة اليمنى للطريق وموازيا لها، وفي السيارة الأوتوماتيكية ضع الذراع على وضع الوقوف P",
     "", ["S3", "S5"], "high"),
    ("parking", 2, "ممنوع الوقوف هنا",
     "على ممرات المشاة والأرصفة، على الجسور وفي الأنفاق، حيث تحجب الإشارات أو اللوحات، أمام مداخل البيوت والمواقف ومحطات الوقود والمستشفيات ومراكز الإسعاف والإطفاء والشرطة",
     "", ["S3", "S4"], "high"),
    ("parking", 3, "قاعدة 15 مترا",
     "ممنوع الوقوف على بعد يقل عن 15 مترا من التقاطعات والميادين والدوارات، وممنوع الوقوف أمام محطات النقل العام",
     "15 مترا", ["S3", "S4"], "high"),
    ("parking", 2, "مواقف لها أصحاب",
     "مواقف أصحاب الهمم لحاملي التصريح فقط، وممنوع الوقوف أمام صنبور إطفاء الحريق",
     "", ["S24"], "medium"),
    ("parking", 2, "لا تحبس أحدا",
     "ممنوع الوقوف المزدوج أو الوقوف في مكان يعرقل خروج مركبة متوقفة، وممنوع الوقوف العشوائي الذي يعطل السير",
     "", ["S3", "S1"], "high"),
    ("parking", 3, "الخروج من الموقف",
     "مرآة، ثم إشارة، ثم التفاتة رأس، ثم انتظر حتى يخلو الطريق، فالمركبات التي على الطريق لها الأولوية",
     "", ["S6", "S3", "S5"], "high"),
    # lights-horn
    ("lights-horn", 1, "متى تشغل الأضواء",
     "من غروب الشمس إلى شروقها، وفي النهار عندما تكون الرؤية غير كافية",
     "", ["S3"], "high"),
    ("lights-horn", 2, "المنخفضة والعالية",
     "الأضواء المنخفضة في المدن والمناطق المأهولة، والعالية فقط على الطرق الخارجية غير المضاءة، وتحول إلى المنخفضة عند اقتراب مركبة من الأمام",
     "", ["S3", "S5"], "high"),
    ("lights-horn", 2, "أضواء التحذير (الفلاشر)",
     "أضواء التحذير للطوارئ فقط مثل التعطل أو التوقف الاضطراري، وليست للقيادة في المطر أو الضباب",
     "للطوارئ فقط", ["S22", "S23"], "high"),
    ("lights-horn", 3, "الأضواء في الضباب",
     "استخدم الأضواء المنخفضة لا العالية، وضاعف مسافة الأمان، وتجنب التجاوز",
     "", ["S22"], "high"),
    ("lights-horn", 2, "المنبه للتنبيه فقط",
     "استخدم المنبه (الزمور) لتفادي خطر فقط، لا بشكل متكرر أو مزعج، ولا والمركبة واقفة",
     "", ["S3"], "high"),
    ("lights-horn", 3, "أماكن وأوقات ممنوع فيها المنبه",
     "قرب المستشفيات والمدارس ودور العبادة، وفي المناطق السكنية من منتصف الليل حتى 6 صباحا",
     "منتصف الليل إلى 6 صباحا", ["S3", "S4", "S6"], "high"),
]
